#! /bin/zsh
# renombra multiples libros a la vez
# by mao2047
loop=true; while $loop; do
fzf -m | while read -r line; do \
    print "$line"; line2=${line:r} && ext=${line:e}; \
    vared -p "introduce nombre: " -c new; \
	print "Mover a: \n | f: filosofía | s: sociología | a: antropologia | t: tecnología | \ 
 | c: ciencias  | i: psicología | l: literatura   | n: religión   |\ 
 |e: pedagogía  | g: guías |*** cualquier otra tecla para salir ***"; \
	vared -p "> " -c a; \
	case $a in \
        f) mv ./$line $HOME/books/filosofia/$new.$ext ;; \
		s) mv ./$line $HOME/books/sociologia/$new.$ext ;; \
		a) mv ./$line $HOME/books/antropologia/$new.$ext ;; \
		t) mv ./$line $HOME/books/tecnologia/$new.$ext ;; \
		c) mv ./$line $HOME/books/ciencias/$new.$ext ;; \
		g) mv ./$line $HOME/books/guias/$new.$ext ;; \
		i) mv ./$line $HOME/books/psicologia/$new.$ext ;; \
		l) mv ./$line $HOME/books/literatura/$new.$ext ;; \
		n) mv ./$line $HOME/books/religion/$new.$ext ;; \
		e) mv ./$line $HOME/books/pedagogia/$new.$ext ;; \
		*) echo "bye"  ;; 
	esac
    unset new;
    unset a;
done

read -s -k "?x para salir: " n; case $n in \
    x) loop=false ;; \
    *) loop=true ;; \
esac
done
