#! /bin/zsh
#a=$(ls | fzf -m); b=$(echo $a | wc | awk '{print $2}'); seq -s " " $b
#a=$(ls | fzf -m); b=$(echo $a | wc | awk '{print $2}'); for i in $(seq -s " " $b) ; do echo "oh yeah"; done
#a=$(ls | fzf -m); b=$(echo $a | wc | awk '{print $2}'); for i in $(seq -s " " $b) ; do read "?> " c; print $c ; done
#a=$(ls | fzf -m); c=$(print $a); print "$a"; for i in $(seq -s " " $(echo $a | wc | awk '{print $2}')) ; do echo $a | while read -r line; do cp $line test1; done; done

fzf -m | while read -r line; do \
    mv $line test1; \
done
